baseURL = "https://agupta54.github.io"
languageCode = "en-us"
title = "Through the lens of mathematics"
theme = "mainroad"
disqusShortname = "disqus_l5sqC5oLSM"

[Author]
    name = "Anirudh Gupta"

[Params]
    subtitle = "Anirudh Gupta"
    description = "Making things simple through math"
    opengraph = true
    twitter_cards = true
    readmore = false
    leftsidebar = false
    authorbox = false 
    post_navigation = true 
    poseSections = ["post"]

[Params.widgets]
    search = true 
    recent_articles = true 
    recent_articles_num = 5
    categories = true 
    tags = true 
    tags_counter = false 
    social_twitter = "anirudh_gupta12"
    
